# Generated by Django 4.0.5 on 2022-07-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despacho',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='id')),
                ('serial', models.CharField(max_length=25, verbose_name='serial')),
                ('marca', models.CharField(blank=True, max_length=25, null=True, verbose_name='marca')),
            ],
        ),
    ]
