# Generated by Django 4.0.5 on 2022-07-09 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Despacho',
            new_name='Repuestos',
        ),
    ]
